hub:
  config:
    JupyterHub:
      admin_access: false
      authenticator_class: dummy
    DummyAuthenticator:
      password: ""
  db:
    type: sqlite-pvc
    pvc:
      storage: 1Gi
  networkPolicy:
    enabled: true

proxy:
  service:
    type: ClusterIP
  chp:
    networkPolicy:
      enabled: true

singleuser:
  image:
    name: quay.io/jupyter/minimal-notebook
    tag: python-3.12
  cpu:
    guarantee: 0.2
    limit: 1
  memory:
    guarantee: 512M
    limit: 2G
  storage:
    capacity: 2Gi
  networkPolicy:
    enabled: true

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false
  podPriority:
    enabled: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

cull:
  enabled: true
  timeout: 1800
  every: 300
